# Importando arquivos EXCEL

## Lendo arquivos .xlsx

In [ ]:
import pandas as pd
from pathlib import Path

#Acrescentar o '..' para pegar pasta datasets global
dataset_vendas = Path.joinpath(Path.cwd(),'..', 'datasets', 'vendas.xlsx')

#id_venda vira índice do dataframe; decimais são definidos com vírgula; uso das três primeiras colunas
df = pd.read_excel(dataset_vendas, index_col=1, decimal=',', usecols=[0,1,2])
df

                            data         filial
id_venda
0        2023-01-20 08:00:56.384         Canoas
1        2023-01-20 08:50:58.756  Florianópolis
2        2023-01-20 11:44:56.777         Canoas
3        2023-01-20 12:07:58.026  Caxias do Sul
4        2023-01-20 12:49:56.607      São Paulo
...                          ...            ...
1995     2023-09-26 08:39:58.719   Porto Alegre
1996     2023-09-26 09:45:56.917        Lajeado
1997     2023-09-26 12:22:56.383         Canoas
1998     2023-09-26 13:01:57.747        Lajeado
1999     2023-09-26 16:32:56.888      São Paulo

[2000 rows x 2 columns]

## Lendo arquivos .csv

In [9]:
dataset_vendas = Path.joinpath(Path.cwd(),'..', 'datasets', 'vendas.csv')

df = pd.read_csv(dataset_vendas, index_col=0, sep=';', decimal=',')
df

,id_venda,filial,vendedor,produto,cliente_nome,cliente_genero,forma_pagamento
data,,,,,,,
2023-01-20 08:00:56.384224,0,Canoas,Luis Fernando,Tenis Nike,Sabrina Rieke,feminino,credito
2023-01-20 08:50:58.755843,1,Florianópolis,Mario Sérgio,Tenis Adidas,Patsy Lovell,feminino,credito
2023-01-20 11:44:56.776745,2,Canoas,Carlos Henrique,Tenis Adidas,John Crandall,masculino,credito
2023-01-20 12:07:58.025749,3,Caxias do Sul,Rodrigo Vanzeloti,Tenis Adidas,Mildred Mcleod,feminino,credito
2023-01-20 12:49:56.606703,4,São Paulo,Cassia Moraes,Tenis NB,Robert Mccormick,masculino,credito
...,...,...,...,...,...,...,...
2023-09-26 08:39:58.718787,1995,Porto Alegre,Luiza Cherobini,Tenis Nike,Glenn Johnson,masculino,credito
2023-09-26 09:45:56.916568,1996,Lajeado,Juliano Faccioni,Tenis Adidas,Robert Roop,masculino,boleto
2023-09-26 12:22:56.382995,1997,Canoas,Luis Fernando,Tenis Adidas,Mary Berg,feminino,credito
2023-09-26 13:01:57.747415,1998,Lajeado,Adriano Soares,Tenis NB,Dianna Alcorn,feminino,credito
2023-09-26 16:32:56.888289,1999,São Paulo,Cassia Moraes,Tenis Fila,Isabelle Mercado,feminino,credito