# Criando tabelas

In [1]:
import pandas as pd

## Criando a partir de listas

In [2]:
data = [1,2,3,4]

df = pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4

## Criando a partir de lista de listas

In [3]:
data = [
        [1,2],
        [3,4],
        [5,6]
    ]

df = pd.DataFrame(data)
df

   0  1
0  1  2
1  3  4
2  5  6

## A partir de dicionário de listas

In [4]:
data = {"Nome": ['Alexandre','Caio','Jonas','Priscilla'],
        "Sobrenome": ['Clemente', 'Alexandre', 'de Sá','Souza']}

df = pd.DataFrame(data)
df

        Nome  Sobrenome
0  Alexandre   Clemente
1       Caio  Alexandre
2      Jonas      de Sá
3  Priscilla      Souza

## Criando com índice

In [5]:
data = {"Nome": ['Alexandre','Caio','Jonas','Priscilla'],
        "Sobrenome": ['Clemente', 'Alexandre', 'de Sá','Souza']}

df = pd.DataFrame(data, index=['pessoa1','pessoa2','pessoa3','pessoa4'])
df

              Nome  Sobrenome
pessoa1  Alexandre   Clemente
pessoa2       Caio  Alexandre
pessoa3      Jonas      de Sá
pessoa4  Priscilla      Souza

## Criando a partir de uma lista de dicionários

In [6]:
data = [
        {'Nome': 'Alexandre', 'Sobrenome': 'Pinheiro'},
        {'Nome': 'Caio', 'Sobrenome': 'Alexandre'},
        {'Nome': 'Jonas', 'Sobrenome': 'de Sá'}
       ]

df = pd.DataFrame(data)
list(df.columns)

['Nome', 'Sobrenome']

In [7]:
list(df.index)

[0, 1, 2]

### Informação de linhas e colunas da matriz

In [8]:
df.shape

(3, 2)