# Visualização de Tabelas com pandas

## Visualização básica no Júpiter

In [10]:
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
data = {"Nome": ['Alexandre','Caio','Jonas','Priscilla'],
        "Sobrenome": ['Clemente', 'Alexandre', 'de Sá','Souza']}

df = pd.DataFrame(data)
df

        Nome  Sobrenome
0  Alexandre   Clemente
1       Caio  Alexandre
2      Jonas      de Sá
3  Priscilla      Souza

## Visualização dos primeiros valores

In [4]:
df.head(2)

        Nome  Sobrenome
0  Alexandre   Clemente
1       Caio  Alexandre

## Visualização dos últimos valores

In [5]:
df.tail(2)

        Nome Sobrenome
2      Jonas     de Sá
3  Priscilla     Souza

## Visualizando tabelas maiores no Jupyter (display.max_rows)

In [8]:
dataset_vendas = Path.joinpath(Path.cwd(),'..', 'datasets', 'vendas.csv')

# Limitando a visualização no Jupyter
pd.set_option('display.max_rows', 100)
df = pd.read_csv(dataset_vendas, index_col=0, sep=';', decimal=',')
df.head()

,id_venda,filial,vendedor,produto,cliente_nome,cliente_genero,forma_pagamento
data,,,,,,,
2023-01-20 08:00:56.384224,0,Canoas,Luis Fernando,Tenis Nike,Sabrina Rieke,feminino,credito
2023-01-20 08:50:58.755843,1,Florianópolis,Mario Sérgio,Tenis Adidas,Patsy Lovell,feminino,credito
2023-01-20 11:44:56.776745,2,Canoas,Carlos Henrique,Tenis Adidas,John Crandall,masculino,credito
2023-01-20 12:07:58.025749,3,Caxias do Sul,Rodrigo Vanzeloti,Tenis Adidas,Mildred Mcleod,feminino,credito
2023-01-20 12:49:56.606703,4,São Paulo,Cassia Moraes,Tenis NB,Robert Mccormick,masculino,credito

## Estilizações

### Formatando floats

In [11]:
df_tempo = pd.DataFrame(np.random.rand(10,2)*5,
                        index=pd.date_range(start="2023-01-01", periods=10),
                        columns=["Porto Alegre", "São Paulo"])

df_tempo.style.format(decimal=',', precision=3)

### Estilizando colunas (ex: 'caixa alta' no nome das colunas)

In [12]:
df_tempo.style.format_index(str.upper, axis=1)

### Estilizando index (ex: formatação da data)

In [14]:
formatar_data = lambda v: v.strftime('%d/%m/%Y')

df_tempo.style.format_index(formatar_data, axis=0)

### Adicionando título no dataframe

In [15]:
df_tempo.style.set_caption('Condições do tempo')

### Adicionando gradiente (formatação condicional)

In [17]:
## vmax-> qual valor vai receber cor mais forte (quanto mais próximo ao valor, mais forte a cor)
## vmin-> inverso do vmax
## cmap-: por meio da matplotlib, permite criar um mapa de cores baseado nos valores vmin, vmax e os da tabela

df_tempo.style.background_gradient(axis=None, vmin=1, vmax=5, cmap="YlGnBu")

### Modificando valores

In [18]:
def condicao_chuva(v):
    if v > 2.75:
        return 'Chuva forte'
    elif v < 1.75:
        return 'Seco'
    else:
        return 'Chuva normal'

df_tempo.style.format(condicao_chuva)

### Juntando tudo o que foi passado anteriormente (criação de função de configuração do style)

In [31]:
def embelezar(styler):
    styler.set_caption('Condição do Tempo (função EMBELEZAR)')
    styler.format(condicao_chuva)
    styler.format_index(formatar_data)
    styler.background_gradient(axis=None, vmin=1, vmax=5, cmap="YlOrRd")

    return styler

df_tempo.style.pipe(embelezar)